"""Minimal smoke test — verifies the app starts and responds.
The real bug-covering tests are generated by the Unit Test Generator agent after fixes are applied.
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app, raise_server_exceptions=False)


def test_app_responds():
    """API is reachable — a basic sanity check."""
    response = client.get("/docs")
    assert response.status_code == 200
